// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.pharmacy.domain;

import java.util.Date;
import org.pharmacy.domain.Letter;
import org.springframework.web.multipart.MultipartFile;

privileged aspect Letter_Roo_JavaBean {
    
    public String Letter.getNumber() {
        return this.number;
    }
    
    public void Letter.setNumber(String number) {
        this.number = number;
    }
    
    public Date Letter.getDate() {
        return this.date;
    }
    
    public void Letter.setDate(Date date) {
        this.date = date;
    }
    
    public String Letter.getSubject() {
        return this.subject;
    }
    
    public void Letter.setSubject(String subject) {
        this.subject = subject;
    }
    
    public boolean Letter.isIsPublished() {
        return this.isPublished;
    }
    
    public void Letter.setIsPublished(boolean isPublished) {
        this.isPublished = isPublished;
    }
    
    public String Letter.getFileName() {
        return this.fileName;
    }
    
    public void Letter.setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    public MultipartFile Letter.getFile() {
        return this.file;
    }
    
    public void Letter.setFile(MultipartFile file) {
        this.file = file;
    }
    
    public String Letter.getNote() {
        return this.note;
    }
    
    public void Letter.setNote(String note) {
        this.note = note;
    }
    
}
